### ISSUE TITLE
在mac下，make遇错，怎么解决？

### ISSUE THREAD

**Issue by luckypoem** [neevek/lightning#1]
hello.

yudeMacBook-Air:build brite$ ls
CMakeCache.txt		Makefile		cmake_install.cmake
CMakeFiles		bin
yudeMacBook-Air:build brite$ ls bin
yudeMacBook-Air:build brite$ make
[  6%] Building C object CMakeFiles/lightning_local.dir/local.c.o
In file included from /Users/brite/lightning/local.c:10:
In file included from /Users/brite/lightning/defs.h:4:
/Users/brite/lightning/encrypt.h:3:10: fatal error: 'openssl/evp.h' file not
      found
#include <openssl/evp.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/lightning_local.dir/local.c.o] Error 1
make[1]: *** [CMakeFiles/lightning_local.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:build brite$

怎么解决？谢谢你

**Comment by neevek** [comment]
lightning 依赖 `openssl` 和 `libuv`，你可以尝试使用以下命令安装依赖：

```bash
brew install openssl
brew install libuv
```

**Comment by luckypoem** [comment]
运行了
brew install openssl
brew install libuv
2者安装成功。
但是运行上面的make时还是遇到同样的错误。

**Comment by neevek** [comment]
如果依赖已经安装成功，但是 make 仍然失败，可以再尝试在 `CMakeLists.txt` 的第 7 行位置加上以下两行：

```cmake
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I/usr/local/opt/openssl/include")
SET(CMAKE_LD_FLAGS "${CMAKE_LD_FLAGS} -L/usr/local/opt/openssl/lib")
```

P.S. 可以使用 `brew --prefix openssl` 查看 openssl 的安装位置。

**Comment by luckypoem** [comment]
谢谢你。现在可以翻＃墙了。不过翻＃墙速度好慢，很久都打不开youtube.com, 在哪里可以优化一下速度呢？

**Comment by neevek** [comment]
你可以 ping 一下你的 proxy 主机，看看 RTT 多少毫秒，看看网络是否稳定，如果有比较严重丢包，肯定会很慢的，而且也没有特别有效地优化方法。

目前 lightning 没有对各种网络情况做特别的优化。但优点是占用内存小，运行稳定（基本上不会有崩溃的情况）。

**Comment by luckypoem** [comment]
现在看youtube流畅了。可能是我的网络问题。你没考虑过推出windows下的客户端程序吗？以便惠及更多的人

**Comment by neevek** [comment]
目前没有打算支持 windows 客户端，但其实这里用的都是跨平台的库，支持 windows 要做的事情其实不多，有兴趣可以 fork。
