### ISSUE TITLE
你这个翻墙术不太稳定啊

### ISSUE THREAD

**Issue by luckypoem** [neevek/lightning#2]
hi。
我最近在用你这个翻墙术，不过有时莫名其妙的翻墙失败，我以为是客户端程序或服务器端程序退出了所致。
但运行命令ps aux|grep lightning_local和ps aux|grep lightning_remote，发现它们都在运行中。但为何会突然翻墙失败呢？
你也遇到过这现象吗

**Comment by neevek** [comment]
你说的这个情况我也遇到过，但我现在没时间查证和 debug。
我试过重启浏览器之后又恢复正常了，猜测可能是本地端口在某些情况下被没正常释放。

**Comment by luckypoem** [comment]
重启客户端也能解决莫名其妙的翻墙失败的问题。
